#ifndef _NAV_BASE_DEFINE_H_
#define _NAV_BASE_DEFINE_H_

enum SamplePolyAreas
{
	SAMPLE_POLYAREA_GROUND = 0,
	SAMPLE_POLYAREA_WATER,
	SAMPLE_POLYAREA_ROAD,
	SAMPLE_POLYAREA_DOOR,
	SAMPLE_POLYAREA_GRASS,
	SAMPLE_POLYAREA_JUMP,
};
enum SamplePolyFlags
{
	SAMPLE_POLYFLAGS_GROUND = 0x01,		// Ability to walk (ground)
	SAMPLE_POLYFLAGS_SWIM = 0x02,		// Ability to swim (water).
	SAMPLE_POLYFLAGS_ROAD = 0x04,		// road
	SAMPLE_POLYFLAGS_DOOR = 0x08,		// Ability to move through doors.
	SAMPLE_POLYFLAGS_JUMP = 0x10,		// Ability to jump.
	SAMPLE_POLYFLAGS_WALK = SAMPLE_POLYFLAGS_GROUND | SAMPLE_POLYFLAGS_ROAD | SAMPLE_POLYAREA_GRASS,
	SAMPLE_POLYFLAGS_DISABLED = 0xf00,		// Disabled polygon
	SAMPLE_POLYFLAGS_ALL = 0x7fff	// All abilities.
};

enum SamplePartitionType
{
	SAMPLE_PARTITION_WATERSHED,
	SAMPLE_PARTITION_MONOTONE,
	SAMPLE_PARTITION_LAYERS,
};

#endif