local Sorting_Layer =
{
	-- BottomMost
	GameWorld = 1,
	-- Bottom
	RootPanel = 2,
	-- Normal
	SubPanel = 3,
	-- Upper
	Dialog = 4,
	-- Top
	NormalTip = 5,
	-- Guide
	Guide = 6,
	-- Topmost
	ImportantTip = 7,

	PowerSaving = 8,
	-- Debug
	Debug = 9
}

local Order_Type =
{
	Fixed = 0,
	Floating = 1
}

local Order_Def =
{
	-- 固定UI 1-40
	Fixed_Count = 40,

	-- 浮动UI 41-80
	Floating_Count = 40,

	-- 预留 81-100
	Top_Count = 20,

	-- UI间隔10
	Step_Count = 10,

	Order_Max = 100,
}

local UISetting =
{
	UI_Table =
	{
		-- ["xx.prefab"] ={ Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FixedOrder = 1, HideMask = 0,CloseMask = 0, FullScreen = true, IM = false },
		-- HideMask: bitMask of which layer to hide, forbid UI from 2 layers can both hide each other; Simply, Dont hide a layer which is higher then yours;
		-- CloseMask: better not to use
		-- FullScreen : If this UI covers a whole area of the screen
		-- IM : wether to use ImageModel Env setting

		["Panel_AuctionSell1.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["Panel_AuctionSell2.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["Panel_Book.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Fixed, FixedOrder = 81 },
		["UI_Buff.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 81 },
		["UI_ChatNew.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["Panel_Circle.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 100 },
		["Panel_CreateRole.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 2 },
		["UI_SceneDialogue.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 10, HideMask = 62 },
		["Panel_Guide.prefab"] = { Layer = Sorting_Layer.Guide, OrderType = Order_Type.Floating },
		["Panel_GuideTrigger.prefab"] = { Layer = Sorting_Layer.Guide, OrderType = Order_Type.Floating },
		["Panel_InExtremis.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 91 },
		["Panel_Instance_Alarm.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Floating },
		["Panel_Instance_NpcTalk.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 40 },
		["Panel_ItemMachining.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 25 },
		["Panel_Loading.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 91, FullScreen = true },
		["Panel_Login.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 15 },
		["UI_Main_Chat.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 5 },
		["Panel_Main_MiniMap.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 3 },
		["Panel_Main_Move.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 6 },
		["Panel_Main_QuestN.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 7 },
		["Panel_Main_SkillNew.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 8 },
		["Panel_MainTips.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 100, ForbidESC = true },
		["Panel_MainTips_Low.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 100, ForbidESC = true },
		["Panel_NpcService.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 11, HideMask = 62 },
		["Panel_OperationTips.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 83 },

		["UI_PetProcess.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true },
		["UI_PetFieldGuide.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, IM = true },
		["UI_PetFightingProperty.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_PetFightSetting.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, IM = true },
		["UI_PetFreeConfirm.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_PetSkillReplace.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_PetAptitudeReset.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_PetResetRecastCntCost.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_CommonCultivate.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },

		-- ["Panel_Producers.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["Panel_QuickTalk.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 9 },
		["Panel_RoleInfoTips.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 28 },
		["Panel_SelectRoleNew.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 1 },
		["Panel_ServerSelect.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Fixed, FixedOrder = 10 },
		["Panel_SetHead.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Fixed, FixedOrder = 2 },
		["Panel_Time.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 85 },
		["UI_Title.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_WorldBoss.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["Panel_WorldMapName.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 5 },
		["UI_3V3Loading.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 90, IM = true },
		["UI_SystemEntrance.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 21 },
		["UI_ChatSet.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Dungeon.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Dungeon_End.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating, CloseMask = 12, HideMask = 6, ForbidESC = true },
		["UI_EquipProcess.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_EquipFortityResult.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_EquipLegendResult.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_EquipRecastResult.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_EquipInheritResult.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_EquipHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_Exterior.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating, HideMask = 4 },
		["UI_Guild.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_Apply.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Guild_Donate.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Guild_List.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_Set.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Guild_Salary.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_AutokillMonster.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_Guild_Smithy.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_SmithyForgeSuccess.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Fixed, FixedOrder = 2 },
		["UI_Head.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 20 },
		["UI_ItemHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_CharmItemHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_InteractiveMenu.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_Lottery.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating, CloseMask = 8 },
		["UI_Mail.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Manual.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Manual_ElementSubDes.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_Map.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Mate.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 40 },
		["UI_MessageBox.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating, FullScreen = false },
		["UI_MessageBox1.prefab"] = { Layer = Sorting_Layer.Guide, OrderType = Order_Type.Fixed, FixedOrder = 40 },
		["UI_MessageBox2.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 99 },
		["UI_MessageBox3.prefab"] = { Layer = Sorting_Layer.Debug, OrderType = Order_Type.Fixed, FixedOrder = 1 },
		["UI_MirrorArena.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true },
		["UI_MoneyHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_ReputationLvTips.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_AutoKillTips.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_CommonTips.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_NPCShop.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_NumberKeyboard.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 27 },
		["UI_QuickUse.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Floating },
		["UI_Ranking.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Rename.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_RewardShow.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_RoleInfoNew.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true },
		["UI_CommonOperate.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 20 },
		["UI_Setting.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating, HideMask = 4 },
		["UI_Skill.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_TeamApplication.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_TeamConfirm.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 39 },
		["UI_TeamCreate.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true },
		["UI_TeamInvite.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_TeamInviteTip.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 40 },
		["UI_TeamMember.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true },
		["UI_TeamSetting.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_TeamMatchingBoard.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_TeamIneligible.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Welfare.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Exterior_AttributeCheck.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating, FixedOrder = 10 },
		["UI_DressAttributeCheck.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating, FixedOrder = 10 },
		["UI_Debug.prefab"] = { Layer = Sorting_Layer.Debug, OrderType = Order_Type.Fixed, FixedOrder = 81 },
		["UI_Log.prefab"] = { Layer = Sorting_Layer.Debug, OrderType = Order_Type.Fixed, FixedOrder = 82 },
		["UI_HuangxinTest.prefab"] = { Layer = Sorting_Layer.Debug, OrderType = Order_Type.Fixed, FixedOrder = 83 },
		["UI_QuestReward.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating, HideMask = 46 },
		["UI_CharmNew.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		-- 新添加
		["UI_Auction.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_ItemList.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_NearCam.prefab"] = { Layer = Sorting_Layer.GameWorld, OrderType = Order_Type.Floating, HideMask = 30 },
		["UI_WorldBossTips.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating, IM = true },
		["UI_HorseRaceLamp.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Floating },
		["UI_Expedition.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_ExpeditionList.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_BattleMiddle.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 11 },
		["UI_PetHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_PetSkillHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_WorldBoss_Settlement.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_PathDistance.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 30 },
		["UI_LegendLibraryHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_RecastLibraryHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_QuenchDescHint.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_PVPHead.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 23 },
		["UI_RuneExpress.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_OtherPlayerInfo.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true },
		["UI_BossEffect.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Fixed, FixedOrder = 96 },
		["Panel_MessageBox.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 15 },
		["UI_Calendar.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_LvUp.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Guild_Pray.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_PrayEvent.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_Guild_PrayHelp.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_Guild_Shop.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_Skill.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_Skill_LvUp.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Damage.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_BattleDamage.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_Guild_Dungeon.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_GuildDungeonReward.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating, FullScreen = false },
		["UI_Guild_Convoy.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_Convoy_Vs.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true },
		["UI_Guild_Convoy_End.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating, ForbidESC = true },
		["UI_Guild_Convoy_Result.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Guild_Defend.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_Battle.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_Guild_Battle_End.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating, ForbidESC = true },
		["UI_Guild_Battle_Result.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Guild_Battle_Kill.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_LegendLibrary.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_QuestList.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_QuestFinishReward.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_QuickTeam.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_Mall.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_MallCommonBuy.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_CommonBuyGuide.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 99 },
		["UI_MallLottery.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_Friend.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_Emotion.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_ArrayLine.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Floating },
		["UI_EyeEntranceTips.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_Wing.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true },
		["UI_ArenaOneMatching.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true, IM = true, ForbidESC = true },
		["UI_ChangeName.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_CharmComposeResult.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_EquipChange.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_BagSort.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_BagDecomposeFilter.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_Guild_Battle_MiniMap.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 3 },
		["UI_EvilValueTip.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_PlayerStrongCompare.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Floating },
		["UI_FullScreenTips.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Floating, HideMask = 30 },
		["UI_SkillDes.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Floating },
		["UI_ItemApproach.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_BuffEnter.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 12 },
		["UI_HotTime.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Fixed, FixedOrder = 81 },
		["UI_ItemApproach.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_FriendFight.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, IM = true },
		["UI_Revive.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 30 },
		["UI_CommonWebView.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating, FullScreen = true },
		["UI_DungeonIntroduction.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Floating },
		["UI_BeginnerDungeonBoss.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Floating, HideMask = 30 },
		["UI_GiftItem.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_QuickMatchConfirm.prefab"] = { Layer = Sorting_Layer.ImportantTip, OrderType = Order_Type.Fixed, FixedOrder = 39 },
		["UI_CreateChat.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_ArrowTip.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_RuleDescription.prefab"] = { Layer = Sorting_Layer.Dialog, OrderType = Order_Type.Fixed, FixedOrder = 31 },
		["UI_BattleResult.prefab"] = { Layer = Sorting_Layer.RootPanel, OrderType = Order_Type.Fixed, FixedOrder = 11 },
		["UI_ServerQueue.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Fixed, FixedOrder = 12 },
		["UI_EnchantWindow.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 20 },
		["UI_PowerSaving.prefab"] = { Layer = Sorting_Layer.PowerSaving, OrderType = Order_Type.Fixed, FixedOrder = 99, FullScreen = true },
		["UI_AppMsgbox.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Fixed, FixedOrder = 86 },
        ["UI_MonsterDropItems.prefab"] = {Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
        ["UI_ReputationIntroduction.prefab"] = {Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
        ["UI_EyeRegionIntroduction.prefab"] = {Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_Strong.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_Activity.prefab"] = { Layer = Sorting_Layer.SubPanel, OrderType = Order_Type.Floating },
		["UI_CommonNotice.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },
		["UI_InquireReward.prefab"] = { Layer = Sorting_Layer.NormalTip, OrderType = Order_Type.Floating },		
	},
}

UISetting.Sorting_Layer = Sorting_Layer
UISetting.Order_Type = Order_Type
UISetting.Order_Def = Order_Def

return UISetting